#!/usr/bin/env php
<?php 
/*
 *	                  ....
 *	                .:   '':.
 *	                ::::     ':..
 *	                ::.         ''..
 *	     .:'.. ..':.:::'    . :.   '':.
 *	    :.   ''     ''     '. ::::.. ..:
 *	    ::::.        ..':.. .''':::::  .
 *	    :::::::..    '..::::  :. ::::  :
 *	    ::'':::::::.    ':::.'':.::::  :
 *	    :..   ''::::::....':     ''::  :
 *	    :::::.    ':::::   :     .. '' .
 *	 .''::::::::... ':::.''   ..''  :.''''.
 *	 :..:::'':::::  :::::...:''        :..:
 *	 ::::::. '::::  ::::::::  ..::        .
 *	 ::::::::.::::  ::::::::  :'':.::   .''
 *	 ::: '::::::::.' '':::::  :.' '':  :
 *	 :::   :::::::::..' ::::  ::...'   .
 *	 :::  .::::::::::   ::::  ::::  .:'
 *	  '::'  '':::::::   ::::  : ::  :
 *	            '::::   ::::  :''  .:
 *	             ::::   ::::    ..''
 *	             :::: ..:::: .:''
 *	               ''''  '''''
 *	
 *
 *	AUTOMAD
 *
 *	Copyright (c) 2018-2020 by Marc Anton Dahmen
 *	http://marcdahmen.de
 *
 *	Licensed under the MIT license.
 *	http://automad.org/license
 */


use Automad\Core as Core;
use Automad\GUI as GUI;
use Automad\System as System;


// Test for CLI.
if (http_response_code() || !defined('STDIN')) {
    exit('CLI only!');
}

define('AUTOMAD', true);
define('AUTOMAD_CONSOLE', true);
define('AM_BASE_DIR', dirname(dirname(__FILE__)));

require AM_BASE_DIR . '/automad/autoload.php'; 
require AM_BASE_DIR . '/automad/const.php'; 

echo 'Automad Console version ' . AM_VERSION . PHP_EOL;

if (empty($argv[1])) {
	
	echo 'The following commands are available: ' . PHP_EOL . PHP_EOL;
	
	foreach (glob(AM_BASE_DIR . '/automad/cli/*') as $command) {
		echo '  ' . str_replace('.php', '', basename($command)) . PHP_EOL;
	}
	
	echo PHP_EOL;
	
} else {
	
	$command = AM_BASE_DIR . '/automad/cli/' . $argv[1] . '.php';
	
	if (is_readable($command)) {
		require $command;
	} else {
		echo 'Command "' . $argv[1] . '" not found!' . PHP_EOL;
	}
	
}