name: automad-dev-nginx

services:
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    depends_on:
      - php
    volumes:
      - ../../:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    image: automad-dev-nginx-php
    build: .
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ../../:/app
      - ../php.ini:/usr/local/etc/php/conf.d/php.ini:ro
