<@~ if @{ colorPageText } @>--color-page-text: @{ colorPageText };<@ end @>
<@~ if @{ colorPageBackground } @>--color-page-bg: @{ colorPageBackground };<@ end @>
<@~ if @{ colorPageBorder } @>--color-page-border: @{ colorPageBorder };<@ end @>
<@~ if @{ colorNavbarText } @>--color-navbar-text: @{ colorNavbarText };<@ end @>
<@~ if @{ colorNavbarBackground } @>--color-navbar-bg: @{ colorNavbarBackground };<@ end @>
<@~ if @{ colorNavbarBorder } @>--color-navbar-border: @{ colorNavbarBorder };<@ end @>
<@~ if @{ colorCardText } @>--color-card-text: @{ colorCardText };<@ end @>
<@~ if @{ colorCardBackground } @>--color-card-bg: @{ colorCardBackground };<@ end @>
<@~ if @{ colorCardBorder } @>--color-card-border: @{ colorCardBorder };<@ end @>
<@~ if @{ colorCodeBackground } @>--color-code-bg: @{ colorCodeBackground };<@ end ~@>