name: 'Build Dist'

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build and push
        run: bash .github/workflows/dist.sh
